# Generated by Django 4.2.3 on 2023-07-19 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=25)),
                ("patient_name", models.CharField(max_length=30)),
                ("patient_about", models.CharField(max_length=255)),
                ("patient_number", models.PositiveIntegerField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name="Doctors",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("img", models.ImageField(upload_to="images/")),
                ("name_doctor", models.CharField(max_length=25)),
                ("specialty", models.CharField(max_length=25)),
                ("instagram_link", models.URLField(max_length=150)),
                ("telegram_link", models.URLField(max_length=150)),
                ("facebook_link", models.URLField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name="Xizmatlar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=25)),
                ("img", models.ImageField(upload_to="images/")),
                ("summary", models.CharField(max_length=75)),
            ],
        ),
    ]
