# Generated by Django 4.2.3 on 2023-07-21 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book_Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patient_name", models.CharField(max_length=25)),
                ("department_name", models.CharField(max_length=50)),
                ("phone_number", models.PositiveIntegerField(max_length=12)),
                ("symptoms", models.CharField(max_length=100)),
                ("date", models.DateField()),
                (
                    "doctorName",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pages.doctors"
                    ),
                ),
            ],
        ),
    ]
